# Generated by Django 4.0.6 on 2022-07-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='recurso',
            field=models.CharField(max_length=100, verbose_name='Recurso'),
        ),
    ]
